version: "3.3"

services:
  api:
    build: .
    image: "hdespaigne/spring-mysql-docker-example:latest"
    container_name: spring-mysql-docker-example
    restart: always
    environment:
      database_host: db
      database_port: 3306
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    build: ./docker/database
    image: "hdespaigne/mysql-for-spring-test:latest"
    container_name: mysql-for-spring-test
    restart: always
      #volumes:
    #- database_data:/var/lib/mysql/
    ports:
      - 33061:3306
#volumes:
  #database_data: